version: '3.8'

services:

  foot-order:
    build: .
    environment:
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
      - TYPEORM_MIGRATIONS_RUN=${TYPEORM_MIGRATIONS_RUN}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_TIME=${TOKEN_TIME}
      - REFRESH_TOKEN_LIFE_TIME=${REFRESH_TOKEN_LIFE_TIME}
      - JWT_RESTORE_SECRET=${JWT_RESTORE_SECRET}
      - DADATA_API_KEY=${DADATA_API_KEY}
      - DADATA_SECRET_KEY=${DADATA_SECRET_KEY}
      - DADATA_URL=${DADATA_URL}

    restart: always
    network_mode: host
    ports:
      - ${BACKEND_PORT}:3000
