version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: foot-order-database
    restart: always
    ports:
      - ${TYPEORM_PORT:-6100}:${INTERNAL_DB_PORT:-5432}
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD:-postgres}
      - POSTGRES_DB=${TYPEORM_DATABASE:-foot-order}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    external: false